include: package:lints/recommended.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    unnecessary_parenthesis: true
    sort_constructors_first: true
    depend_on_referenced_packages: false
