name: agora_token_service
description: Unofficial library for generating Agora.io WebRTC tokens.
version: 0.1.0
homepage: https://github.com/rasitayaz/agora-token-service-dart
repository: https://github.com/rasitayaz/agora-token-service-dart
issue_tracker: https://github.com/rasitayaz/agora-token-service-dart/issues

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  crc32_checksum: ^0.0.2
  crypto: ^3.0.2
